### ISSUE TITLE
On load SPIERSedit sets the zoom to 10%

### ISSUE THREAD

**Issue by alanspencer** [palaeoware/SPIERS#10]
**Describe the bug**
On loading a SPE file SPIERSedit is setting the zoom factor to 10%. Which is probably due to the value being set as null or 0 on file read,or the zoom factor is no longer being saved to the SPV correctly.

**To Reproduce**
1. Open a SPV file.
2. Change zoom factor
3. Save file and close
4. Reopen and see error

**Expected behavior**
Zoom factor should be saved to SPE files and then used on file load to set the current zoom factor.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version v3.0.0-rc.2

**Comment by RussellGarwood** [comment]
This doesn't happen on Linux - does it still on Windows, Alan?

**Comment by alanspencer** [comment]
This is still an issue. It appears when an SPE file is opened that was last saved in an older version of SPIERSedit. Once the file has been opened and the zoom level changed in v3.0.0 it seems the new zoom level is correctly saved to the file and read in on next file load. Closing this issue down for now as it is not a mojor problem.

**Comment by RussellGarwood** [comment]
This has now been fixed - and changes in zoom persist across sessions.
