### ISSUE TITLE
TIFF files won't load in SPIERSalign

### ISSUE THREAD

**Issue by alanspencer** [palaeoware/SPIERS#13]
**Describe the bug**
I am running into an issue with loading images onto SPIERSalign.  I have a stack of TIFF files that I downloaded off of Digimorph and SPIERSalign cannot find them in when I reach the file in the directory.  I have tried to save these images as png, bitmap, and jpeg formats on Slicer so that SPIERSalign can recognize them but with no luck.  What can I do to get SPIERSalign to read these files?

[from email]

**Comment by RussellGarwood** [comment]
Tiff support added to both align and edit, and tested (but to a limited extent in the latter). All seems to work OK so far.
