### ISSUE TITLE
File associations on Mac

### ISSUE THREAD

**Issue by RussellGarwood** [palaeoware/SPIERS#26]
**Describe the bug**

There is an issue with SPIERSview and SPIERSedit not picking up the filename and opening it via the macOS "event(QEvent *)" file opener event in main. 

**To Reproduce**
To do file association: the file assoication with .spv -> SPIERSview or .spe -> SPIERSedit can be manually created by selecting the "All Applciations" rather than "Recommend Application" from the drop down list. Though looking at this we should be able to manually edit/get QT/QMake to alter the Info.plist file in the application bundle to get macOS to do this automatically. 

EVEN after this change double clicking on .spv/.spe still only launches the software but does not load the selected file.

**Expected behavior**
It should load the .spv/.spe (or other associated files)

**Desktop (please complete the following information):**
MacOS

**Comment by alanspencer** [comment]
Update: https://github.com/palaeoware/SPIERS/commit/00449fcac7d9d64813e834c15f226d6ac35764aa appears to have fixed the SPIERSview file opening via assoicated file double click.

**Comment by alanspencer** [comment]
Commit https://github.com/palaeoware/SPIERS/commit/cfb4b3f75104907f7bfcfa9156eee1b8207cd3a7 seems to have fixed the previous fix for SPIERSedit

Commit https://github.com/palaeoware/SPIERS/commit/b2f411e99328d22a2a61a61d660ad84d0a29846e seems to have fixed the previous fix for SPIERSview

**Comment by RussellGarwood** [comment]
Double click on view seems to work. Based on fresh install:
-- I had to manually associate .spe with spiers edit
-- On load edit creates a .spe_backup file - was this for debugging?
-- Edit doesn't seem to launch view happily on my install, I'm afraid - no response the first few times I hit F12, though this does create the SPV
-- I think edit managed to launch view once, once I had done this, but when it did it then prompted me to get the file through a dialogue.

I want to do further testing tomorrow to be sure of above.

**Comment by RussellGarwood** [comment]
Completed and tested with commit cfb4b3f75104907f7bfcfa9156eee1b8207cd3a7 - thanks Alan!
