### ISSUE TITLE
SPIERSView Won't Open

### ISSUE THREAD

**Issue by zpatty** [palaeoware/SPIERS#29]
SPIERSView fails to open when running the executable. The SPIERS logo briefly appears, followed by the program window for a fraction of a second, then the whole thing shuts down. This is following a fresh build of SPIERS with all dependencies installed. This is the Linux version of the software and the problem was observed on both Ubuntu 18.04 and 20.04.

**Comment by RussellGarwood** [comment]
@zpatty  - unable to reproduce this issue on fresh builds on 18.04 and 20.04, but suspect it's the file dialogue that SPIESview opens by default causing the crash. I've changed the default directory from build to desktop with commit 4c9b663 - please can you pull and see if this fixes the issue?

**Comment by zpatty** [comment]
It's now working on 18.04 but the same issue occurs on 20.04.

**Comment by RussellGarwood** [comment]
OK - any chance, to just make sure it's not the same issue persisting, can you double check that in the 20.04 build lines 268-272 of mainwindow.cpp are:

      fname = QFileDialog::getOpenFileName(
                    this,
                    "Select " + QString(PRODUCTNAME) + " file",
                    QStandardPaths::writableLocation(QStandardPaths::DesktopLocation),
                    QString(PRODUCTNAME) + " files (*.spv *.sp2 *spvf *.xml *.vaxml)");
        FilterKeys = true;

Then clean all projets and rebuild, if you're using QT Creator, or delete the old build folder if you're building from command line - just in case it's something to do with the shadow-build system. 

Thanks

**Comment by RussellGarwood** [comment]
Oh, and if the latter perhaps rerun qmake too.

**Comment by RussellGarwood** [comment]
Given lack of response, assume this is now fixed - closing issue
