### ISSUE TITLE
New masks/segments/curves all appear as the same colour rather than changing

### ISSUE THREAD

**Issue by RussellGarwood** [palaeoware/SPIERS#6]
**Describe the bug**
SPIERS used to give each new mask/segment/curve its own random colour - now all appear as the same tone and need to be changed. I came across this as checking after cleaning the code in globals.cpp, and I assumed I had messed it up. However, going back to old versions of the source code and recompiling it looks like it's been an issue for a while. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new mask/segment/curve.
2. Look at their colour in the menu

**Expected behavior**
Each new instance of one of these objects should be a different colour

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by marksutton** [comment]
This DOES work in windows - just tested it. Something related to Linux then, but no idea what. I'm looking for the source atm!

**Comment by marksutton** [comment]
It's globals.cpp, lines 106-109, Mask constructor. Can't see any obvious problem with it, unless qrand and RAND_MAX behave differently on linux? They really shouldn't! You'll need to test it on your system I'm afraid - the problem might be with the display widget rather than the actual creation of the colours in the Mask constructor.

**Comment by RussellGarwood** [comment]
Thanks - I was going to ask you to check, as I don't recall it being an issue on Windows last time I used it. Did you test it with the version I pushed half an hour ago? If not, please can you quickly do so to check that all is OK with the C++ style casting?

**Comment by RussellGarwood** [comment]
Worked this out - will push a fix later this evening!

**Comment by RussellGarwood** [comment]
I pushed a fix to this last night - qrand was maxing out a plain int on Linux compiler. I assume on windows either the standard size of an int is larger, or the compiler was working out from qrand that it needed to be a long int. To fix I explicitly made n in the constructor of masks, segments, and curves, quint64: this makes it work on Linux and shouldn't break it on windows, I hope.
