### ISSUE TITLE
Screen capture in SPIERSview not saving JPEG or TIFF images

### ISSUE THREAD

**Issue by alanspencer** [palaeoware/SPIERS#7]
**Describe the bug**
The screen capture function is not saving .jpg image files. It is however saving BMP and PNG images.

**To Reproduce**
1. Go to 'File'
2. Click on 'Screen capture'
3. Select either '.jpg' ot '.tif' as the file extension.
4. No file is saved.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by RussellGarwood** [comment]
All formats work in Linux, as long as you put the file extension manually on the end of the file name. None work if you don't do this. It could be worth, when fixing this, adding extensions to the end of the file name on dialogue close if they aren't already there.

**Comment by alanspencer** [comment]
The issue was found with the QT plugin imageformats .dll requiring missing .dll and silently failing. These missing .dlls have now been identified and will be included in future Window binaries.
