### ISSUE TITLE
Brush in SPIERSedit does not resize on file load to saved brush size

### ISSUE THREAD

**Issue by alanspencer** [palaeoware/SPIERS#9]
**Describe the bug**
On a SPE file load the brush size does not resize to the saved brush size. However, the brush size widget in the main toolbar is being updated on load.

**To Reproduce**
1. Load a SPE file that has a none default brush size saved.

**Expected behavior**
On load the brush size seen should match the lasted saved brush size.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version v3.0.0-rc.2

**Comment by RussellGarwood** [comment]
This is now fixed, and persists between sessions.
